### ISSUE TITLE
有时间，帮忙更新一下, 访问修饰符吗?

### ISSUE THREAD

**Issue by rgmyyw** [Mebsunny/swiftScan#1]
RT: 

有时间，帮忙更新一下, 访问修饰符吗? ，有多都是interner  外面都无法调用啊

**Comment by Mebsunny** [comment]
默认就是internal 你换成open试试呢

**Comment by SamXZP** [comment]
> RT:
> 
> 有时间，帮忙更新一下, 访问修饰符吗? ，有多都是interner 外面都无法调用啊

默认就是internal 你换成open试试呢

**Comment by rgmyyw** [comment]
> > RT:
> > 有时间，帮忙更新一下, 访问修饰符吗? ，有多都是interner 外面都无法调用啊
> 
> 默认就是internal 你换成open试试呢

好的， 我自己fork 了一份。
