### ISSUE TITLE
怎么引入你的fork版本呢

### ISSUE THREAD

**Issue by XingXiaoWu** [Mebsunny/swiftScan#2]

**Comment by SamXZP** [comment]
你可以直接拖到工程文件，他这个只是前期在我调研的时候弄的，仅作为学习用，没有制作成pod。
我自己的项目最后也是用的系统扫描，自己写的也很简单。

**Comment by XingXiaoWu** [comment]
我直接追加你的git地址pod下来了，准备看看。
自己写虽然简单，但是能偷懒还是偷懒，哈哈哈哈
